version: '3'
services:
  database:
    image: postgres:11.5-alpine
    container_name: db-container
    volumes:
      - data-volume:/data/dashboard_db
    environment:
      - POSTGRES_USER=
      - POSTGRES_PASSWORD=
      - POSTGRES_DB=
    ports:
      - '5432:5432'
    networks:
      - default

volumes:
  data-volume:
    external: true
