apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
type: Opaque
data:
  db-user: ZGFzaGJvYXJkaw== #Base64 Encoded echo -n <username> | base64
  db-password: cEAxMjM2N3dvcmQh #Base64 Encoded