version: '3.1'
services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: dashboardk
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dashboark
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "54333:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s