apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: prasilabs/dashboardk:0.0.1-preview
          ports:
            - containerPort: 80
          env:
            - name: DB_USER_NAME
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: db-user
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: db-password
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: backend-configs
                  key: db-schema-name
            - name: DB_URL
              valueFrom:
                configMapKeyRef:
                  name: backend-configs
                  key: db-url
          volumes:
            - name: config
              configMap:
                name: dashboard-config
                items:
                  - key: "dashboard.yml"
                    path: ../dashboard.yml
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  type: NodePort
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80 #should be same as container port
      nodePort: 30001 #should be 30000 - 32767